# Google Apps dependencies
PRODUCT_COPY_FILES += \
    vendor/google_apps/proprietary/system/etc/permissions/com.google.android.camera2.xml:system/etc/permissions/com.google.android.camera2.xml:google_apps \
    vendor/google_apps/proprietary/system/etc/permissions/com.google.android.dialer.support.xml:system/etc/permissions/com.google.android.dialer.support.xml:google_apps \
    vendor/google_apps/proprietary/system/etc/permissions/com.google.android.maps.xml:system/etc/permissions/com.google.android.maps.xml:google_apps \
    vendor/google_apps/proprietary/system/etc/permissions/com.google.android.media.effects.xml:system/etc/permissions/com.google.android.media.effects.xml:google_apps \
    vendor/google_apps/proprietary/system/etc/permissions/com.google.widevine.software.drm.xml:system/etc/permissions/com.google.widevine.software.drm.xml:google_apps \
    vendor/google_apps/proprietary/system/etc/permissions/features.xml:system/etc/permissions/features.xml:google_apps \
    vendor/google_apps/proprietary/system/etc/preferred-apps/google.xml:system/etc/preferred-apps/google.xml:google_apps \
    vendor/google_apps/proprietary/system/framework/android.test.runner.jar:system/framework/android.test.runner.jar:google_apps \
    vendor/google_apps/proprietary/system/framework/com.android.location.provider.jar:system/framework/com.android.location.provider.jar:google_apps \
    vendor/google_apps/proprietary/system/framework/com.android.media.remotedisplay.jar:system/framework/com.android.media.remotedisplay.jar:google_apps \
    vendor/google_apps/proprietary/system/framework/com.google.android.camera2.jar:system/framework/com.google.android.camera2.jar:google_apps \
    vendor/google_apps/proprietary/system/framework/com.google.android.dialer.support.jar:system/framework/com.google.android.dialer.support.jar:google_apps \
    vendor/google_apps/proprietary/system/framework/com.google.android.maps.jar:system/framework/com.google.android.maps.jar:google_apps \
    vendor/google_apps/proprietary/system/framework/com.google.android.media.effects.jar:system/framework/com.google.android.media.effects.jar:google_apps \
    vendor/google_apps/proprietary/system/framework/com.google.widevine.software.drm.jar:system/framework/com.google.widevine.software.drm.jar:google_apps \
    vendor/google_apps/proprietary/system/lib/libAppDataSearch.so:system/lib/libAppDataSearch.so:google_apps \
    vendor/google_apps/proprietary/system/lib/libconscrypt_gmscore_jni.so:system/lib/libconscrypt_gmscore_jni.so:google_apps \
    vendor/google_apps/proprietary/system/lib/libcronet.so:system/lib/libcronet.so:google_apps \
    vendor/google_apps/proprietary/system/lib/libdirect-audio.so:system/lib/libdirect-audio.so:google_apps \
    vendor/google_apps/proprietary/system/lib/libfacelock_jni.so:system/lib/libfacelock_jni.so:google_apps \
    vendor/google_apps/proprietary/system/lib/libfilterpack_facedetect.so:system/lib/libfilterpack_facedetect.so:google_apps \
    vendor/google_apps/proprietary/system/lib/libgames_rtmp_jni.so:system/lib/libgames_rtmp.jni.so:google_apps \
    vendor/google_apps/proprietary/system/lib/libgcam.so:system/lib/libgcam.so:google_apps \
    vendor/google_apps/proprietary/system/lib/libgcam_swig_jni.so:system/lib/libgcam_swig_jni.so:google_apps \
    vendor/google_apps/proprietary/system/lib/libgcastv2_base.so:system/lib/libgcastv2_base.so:google_apps \
    vendor/google_apps/proprietary/system/lib/libgcastv2_support.so:system/lib/libgcastv2_support.so:google_apps \
    vendor/google_apps/proprietary/system/lib/libgmscore.so:system/lib/libgmscore.so:google_apps \
    vendor/google_apps/proprietary/system/lib/libgms-ocrclient.so:system/lib/libgms-ocrclient.so:google_apps \
    vendor/google_apps/proprietary/system/lib/libgoogle_hotword_jni.so:system/lib/libgoogle_hotword_jni.so:google_apps \
    vendor/google_apps/proprietary/system/lib/libgoogle_recognizer_jni_l.so:system/lib/libgoogle_recognizer_jni_l.so:google_apps \
    vendor/google_apps/proprietary/system/lib/libgoogle_speech_jni.so:system/lib/libgoogle_speech_jni.so:google_apps \
    vendor/google_apps/proprietary/system/lib/libgoogle_speech_micro_jni.so:system/lib/libgoogle_speech_micro_jni.so:google_apps \
    vendor/google_apps/proprietary/system/lib/libjgcastservice.so:system/lib/libjgcastservice.so:google_apps \
    vendor/google_apps/proprietary/system/lib/libjni_jpegutil.so:system/lib/libjni_jpegutil.so:google_apps \
    vendor/google_apps/proprietary/system/lib/libjni_tinyplanet.so:system/lib/libjni_tinyplanet.so:google_apps \
    vendor/google_apps/proprietary/system/lib/libjpeg.so:system/lib/libjpeg.so:google_apps \
    vendor/google_apps/proprietary/system/lib/libleveldbjni.so:system/lib/libleveldbjni.so:google_apps \
    vendor/google_apps/proprietary/system/lib/liblightcycle.so:system/lib/liblightcycle.so:google_apps \
    vendor/google_apps/proprietary/system/lib/libnativehelper_compat_libc++.so:system/lib/libnativehelper_compat_libc++.so:google_apps \
    vendor/google_apps/proprietary/system/lib/libNearbyApp.so:system/lib/libNearbyApp.so:google_apps \
    vendor/google_apps/proprietary/system/lib/libpatts_engine_jni_api.so:system/lib/libpatts_engine_jni_api.so:google_apps \
    vendor/google_apps/proprietary/system/lib/libpatts_engine_jni_api_ub.210303120.so:system/lib/libpatts_engine_jni_api_ub.210303120.so:google_apps \
    vendor/google_apps/proprietary/system/lib/libpatts_engine_jni_api_ub.210303130.so:system/lib/libpatts_engine_jni_api_ub.210303130.so:google_apps \
    vendor/google_apps/proprietary/system/lib/librefocus.so:system/lib/librefocus.so:google_apps \
    vendor/google_apps/proprietary/system/lib/librs.layered_filter_fast_f32.so:system/lib/librs.layered_filter_fast_f32.so:google_apps \
    vendor/google_apps/proprietary/system/lib/librsjni.so:system/lib/librsjni.so:google_apps \
    vendor/google_apps/proprietary/system/lib/libRSSupport.so:system/lib/libRSSupport.so:google_apps \
    vendor/google_apps/proprietary/system/lib/libspeexwrapper.so:system/lib/libspeexwrapper.so:google_apps \
    vendor/google_apps/proprietary/system/lib/libspeexresampler.so:system/lib/libspeexresampler.so:google_apps \
    vendor/google_apps/proprietary/system/lib/libsslwrapper_jni.so:system/lib/libsslwrapper_jni.so:google_apps \
    vendor/google_apps/proprietary/system/lib/libvariablespeed.so:system/lib/libvariablespeed.so:google_apps \
    vendor/google_apps/proprietary/system/lib/libvcdecoder_jni.so:system/lib/libvcdecoder_jni.so:google_apps \
    vendor/google_apps/proprietary/system/lib/libwearable-selector.so:system/lib/libwearable-selector.so:google_apps \
    vendor/google_apps/proprietary/system/lib/libWhisper.so:system/lib/libWhisper.so:google_apps \
    vendor/google_apps/proprietary/system/usr/srec/en-US/c_fst:system/usr/srec/en-US/c_fst:google_apps \
    vendor/google_apps/proprietary/system/usr/srec/en-US/clg:system/usr/srec/en-US/clg:google_apps \
    vendor/google_apps/proprietary/system/usr/srec/en-US/commands.abnf:system/usr/srec/en-US/commands.abnf:google_apps \
    vendor/google_apps/proprietary/system/usr/srec/en-US/compile_grammar.config:system/usr/srec/en-US/compile_grammar.config:google_apps \
    vendor/google_apps/proprietary/system/usr/srec/en-US/contacts.abnf:system/usr/srec/en-US/contacts.abnf:google_apps \
    vendor/google_apps/proprietary/system/usr/srec/en-US/dict:system/usr/srec/en-US/dict:google_apps \
    vendor/google_apps/proprietary/system/usr/srec/en-US/dictation.config:system/usr/srec/en-US/dictation.config:google_apps \
    vendor/google_apps/proprietary/system/usr/srec/en-US/dnn:system/usr/srec/en-US/dnn:google_apps \
    vendor/google_apps/proprietary/system/usr/srec/en-US/endpointer_dictation.config:system/usr/srec/en-US/endpointer_dictation.config:google_apps \
    vendor/google_apps/proprietary/system/usr/srec/en-US/endpointer_voicesearch.config:system/usr/srec/en-US/endpointer_voicesearch.config:google_apps \
    vendor/google_apps/proprietary/system/usr/srec/en-US/ep_acoustic_model:system/usr/srec/en-US/ep_acoustic_model:google_apps \
    vendor/google_apps/proprietary/system/usr/srec/en-US/g2p_fst:system/usr/srec/en-US/g2p_fst:google_apps \
    vendor/google_apps/proprietary/system/usr/srec/en-US/grammar.config:system/usr/srec/en-US/grammar.config:google_apps \
    vendor/google_apps/proprietary/system/usr/srec/en-US/hclg_shotword:system/usr/srec/en-US/hclg_shotword:google_apps \
    vendor/google_apps/proprietary/system/usr/srec/en-US/hmmlist:system/usr/srec/en-US/hmmlist:google_apps \
    vendor/google_apps/proprietary/system/usr/srec/en-US/hmm_symbols:system/usr/srec/en-US/hmm_symbols:google_apps \
    vendor/google_apps/proprietary/system/usr/srec/en-US/hotword.config:system/usr/srec/en-US/hotword.config:google_apps \
    vendor/google_apps/proprietary/system/usr/srec/en-US/hotword_classifier:system/usr/srec/en-US/hotword_classifier:google_apps \
    vendor/google_apps/proprietary/system/usr/srec/en-US/hotword_normalizer:system/usr/srec/en-US/hotword_normalizer:google_apps \
    vendor/google_apps/proprietary/system/usr/srec/en-US/hotword_prompt.txt:system/usr/srec/en-US/hotword_prompt.txt:google_apps \
    vendor/google_apps/proprietary/system/usr/srec/en-US/hotword_word_symbols:system/usr/srec/en-US/hotword_word_symbols:google_apps \
    vendor/google_apps/proprietary/system/usr/srec/en-US/metadata:system/usr/srec/en-US/metadata:google_apps \
    vendor/google_apps/proprietary/system/usr/srec/en-US/normalizer:system/usr/srec/en-US/normalizer:google_apps \
    vendor/google_apps/proprietary/system/usr/srec/en-US/norm_fst:system/usr/srec/en-US/norm_fst:google_apps \
    vendor/google_apps/proprietary/system/usr/srec/en-US/offensive_word_normalizer:system/usr/srec/en-US/offensive_word_normalizer:google_apps \
    vendor/google_apps/proprietary/system/usr/srec/en-US/phonelist:system/usr/srec/en-US/phonelist:google_apps \
    vendor/google_apps/proprietary/system/usr/srec/en-US/phone_state_map:system/usr/srec/en-US/phone_state_map:google_apps \
    vendor/google_apps/proprietary/system/usr/srec/en-US/rescoring_lm:system/usr/srec/en-US/rescoring_lm:google_apps \
    vendor/google_apps/proprietary/system/usr/srec/en-US/wordlist:system/usr/srec/en-US/wordlist:google_apps \
    vendor/google_apps/proprietary/system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.8/landmark_group_meta_data.bin:system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.8/landmark_group_meta_data.bin:google_apps \
    vendor/google_apps/proprietary/system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.8/left_eye-y0-yi45-p0-pi45-r0-ri20.lg_32-tree7-wmd.bin:system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.8/left_eye-y0-yi45-p0-pi45-r0-ri20.lg_32-tree7-wmd.bin:google_apps \
    vendor/google_apps/proprietary/system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.8/nose_base-y0-yi45-p0-pi45-r0-ri20.lg_32-tree7-wmd.bin:system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.8/nose_base-y0-yi45-p0-pi45-r0-ri20.lg_32-tree7-wmd.bin:google_apps \
    vendor/google_apps/proprietary/system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.8/right_eye-y0-yi45-p0-pi45-r0-ri20.lg_32-3-tree7-wmd.bin:system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.8/right_eye-y0-yi45-p0-pi45-r0-ri20.lg_32-3-tree7-wmd.bin:google_apps \
    vendor/google_apps/proprietary/system/vendor/pittpatt/models/detection/yaw_roll_face_detectors.7.1/head-y0-yi45-p0-pi45-r0-ri30.4a-v24-tree7-2-wmd.bin:system/vendor/pittpatt/models/detection/yaw_roll_face_detectors.7.1/head-y0-yi45-p0-pi45-r0-ri30.4a-v24-tree7-2-wmd.bin:google_apps \
    vendor/google_apps/proprietary/system/vendor/pittpatt/models/detection/yaw_roll_face_detectors.7.1/head-y0-yi45-p0-pi45-rn30-ri30.5-v24-tree7-2-wmd.bin:system/vendor/pittpatt/models/detection/yaw_roll_face_detectors.7.1/head-y0-yi45-p0-pi45-rn30-ri30.5-v24-tree7-2-wmd.bin:google_apps \
    vendor/google_apps/proprietary/system/vendor/pittpatt/models/detection/yaw_roll_face_detectors.7.1/head-y0-yi45-p0-pi45-rp30-ri30.5-v24-tree7-2-wmd.bin:system/vendor/pittpatt/models/detection/yaw_roll_face_detectors.7.1/head-y0-yi45-p0-pi45-rp30-ri30.5-v24-tree7-2-wmd.bin:google_apps \
    vendor/google_apps/proprietary/system/vendor/pittpatt/models/detection/yaw_roll_face_detectors.7.1/pose-r.8.1.bin:system/vendor/pittpatt/models/detection/yaw_roll_face_detectors.7.1/pose-r.8.1.bin:google_apps \
    vendor/google_apps/proprietary/system/vendor/pittpatt/models/detection/yaw_roll_face_detectors.7.1/pose-y-r.8.1.bin:system/vendor/pittpatt/models/detection/yaw_roll_face_detectors.7.1/pose-y-r.8.1.bin:google_apps \
    vendor/google_apps/proprietary/system/vendor/pittpatt/models/recognition/face.face.y0-y0-71-N-tree_7-wmd.bin:system/vendor/pittpatt/models/recognition/face.face.y0-y0-71-N-tree_7-wmd.bin:google_apps \

PRODUCT_PACKAGES += \
    CloudPrint2 \
    ConfigUpdater \
    Exchange3Google \
    FaceLock \
    GoogleCalendar \
    GoogleCamera \
    GoogleContactsSyncAdapter \
    GoogleHome \
    QuickOffice \
    GmsCore \
    GoogleBackupTransport \
    GoogleFeedback \
    GoogleLoginService \
    GoogleOneTimeInitializer \
    GooglePartnerSetup \
    GoogleServicesFramework \
    Phonesky \
    SetupWizard \
    Velvet
